---
title: "Assignment2 37810"
author: "Yanfei Zhou"
date: "21/10/2018"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(fig.width=12, fig.height=8) 
```

```{r}
########## Creating test data ##############
#set true values to parameter A
trueA <- 5
#set true values to parameter B
trueB <- 0
#set true values to parameter sd
trueSd <- 10
#set sample size
sampleSize <- 31
# create independent x-values, in this case from -15 to 15
x <- (-(sampleSize-1)/2):((sampleSize-1)/2)
# create dependent values according to ax + b + N(0,sd), with parameters all equal to their true values
y <-  trueA * x + trueB + rnorm(n=sampleSize,mean=0,sd=trueSd)
#plot y and x, we can see a clear linear relationship
plot(x,y, main="Test Data")

source("functions.R")


# Example: plot the likelihood profile of the slope a
# define a function which inputs a slope parameter x, calculate the likelihood for x, with real parameters b and sd
#slopevalues <- function(x){return(likelihood(c(x, trueB, trueSd)))}
# apply the above function to a range of x values (from 3 to 7 by 0.05), calculate the likelihood at each value
#slopelikelihoods <- lapply(seq(3, 7, by=.05), slopevalues )
# plot the loglikelihood for x, we see the plot peaks at around 5, which is equal to the true value we set previously
#plot (seq(3, 7, by=.05), slopelikelihoods , type="l", xlab = "values of slope parameter", ylab = "Log likelihood")





#example
#startvalue = c(4,0,10)
#chain = run_metropolis_MCMC(startvalue, 10000)
# set a burnIn value as the first steps of the algorithm may be biased by initial value, thus we discard them for the further analysis
#burnIn = 5000
#calculate the acceptance rate by 1-rejection rate
#acceptance = 1-mean(duplicated(chain[-(1:burnIn),]))






```





